version: 2

before:
  hooks:
    - cmd: bun install
      dir: web
    - cmd: bun run build
      dir: web
    - cmd: mkdir -p internal/managementasset/static
    - cmd: cp web/dist/index.html internal/managementasset/static/management.html

builds:
  - id: "llmhub"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    main: ./cmd/server/
    binary: llmhub
    ldflags:
      - -s -w -X 'main.Version={{.Version}}' -X 'main.Commit={{.ShortCommit}}' -X 'main.BuildDate={{.Date}}'
archives:
  - id: "llmhub"
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{- if eq .Arch "arm64" -}}aarch64{{- else -}}{{ .Arch }}{{- end -}}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - README_CN.md
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
